# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'exoltenone/expensish-api:$(build.buildId)'

# Î» dotnet build expensish-api\Expensish-api.sln
steps:
- script: dir
  workingDirectory: $(Agent.BuildDirectory)
  displayName: List contents of a folder BuildDirectory
- script: dir
  workingDirectory: $(Agent.HomeDirectory)
  displayName: List contents of a folder HomeDirectory
- script: dir
  workingDirectory: $(Agent.WorkFolder)
  displayName: List contents of a folder WorkFolder
- script: dir
  workingDirectory: $(Build.SourcesDirectory)
  displayName: List contents of a folder Build.SourcesDirectory
- script: |
    dotnet build --configuration $(buildConfiguration) expensish-api\Expensish-api.sln
  displayName: 'expensish api'
# - script: docker build -f Dockerfile -t $(imageName) .
#   displayName: 'docker build'
