version: '3.1'

services:
  expensish-reverseproxy:
    build: './expensish-reverse-proxy'
    image: "exoltenone/expensish-reverseproxy:${TAG}"
    ports:
        - 9090:8080
        - 9091:8081
    restart: always
    depends_on:
      - expensish-app
      - expensish-api
  expensish-app: 
    build: './expensish-app'
    # depends_on:
    #   - expensish-reverseproxy
    image: exoltenone/expensish:${TAG}
  expensish-api:
    build: './expensish-api/Expensish.Api'
    # depends_on:
    #   - expensish-reverseproxy
    image: exoltenone/expensish-api:${TAG}