version: '3.1'

services:
  expensish-reverseproxy:
    build: './expensish-reverse-proxy'
    image: exoltenone/expensish-reverseproxy:0.3
    ports:
        - 8080:8080
        - 8081:8081
    restart: always
    depends_on:
      - expensish-app
      - expensish-api
  expensish-app: 
    build: './expensish-app'
    # depends_on:
    #   - expensish-reverseproxy
    image: exoltenone/expensish:0.3
  expensish-api:
    build: './expensish-api/Expensish.Api'
    # depends_on:
    #   - expensish-reverseproxy
    image: exoltenone/expensish-api:0.3